### PR TITLE
Fix StartWithWindows for FBDashboard and FBuildWorker

### PR DESCRIPTION
**Pull request by Nesquick0**
After moving FBDashboard.shadow.exe to temp directory, it can't find original binary to setup path for windows startup.
I was trying to find how to remember path to original file, but I think only way is through cmd line parameter.

Second issue was that FBuildWorker.exe was search in working directory in "FBuild\FBuildWorker.exe" but when program is started from windows register, working directory is "c:\Windows\System32". So I added searching in relative path to running binary and copy FBuildWorker.exe also to temp directory. Moved both to subfolder "FBDashboard" in Temp directory.

Note: I'm not C# programmer so I'm sorry if I did something inappropriate.

### CODE REVIEW

**Comment by hillin** [comment]
Thanks for highlighting this problem! 

Since the shadow executable is never supposed to be run directly, I think it would be better to simply prevent a shadow process from touching the registry (which is redundant because its *parent* process always setup the registry before spawning it).

**Comment by Nesquick0** [comment]
I have probably similar idea, because I saw, that in regedit it is changed twice.

But I'm not sure how saving values for this project work, but I found "user.config" in AppData\Local\Hillinworks\FBDashboard.shadow.exe_...".

What I understand, that this file is only created when save() is called. Original exe only read StartWithWindows (so it is always true), and start Shadow. So Shadow is only exe which is changing saved values and can load false for StartWithWindows. For me this is why I have to have path to original exe so I can change registry values. Also user is only working with Shadow so this exe must be able to change registry.

**Comment by hillin** [comment]
Yes, this is exactly the most complex part of this issue. .NET's `ApplicationSettingsBase` class handles the per-application-instance setting storage in a quite sealed manner, so in order to share settings between the "parent" and the shadow assemblies, we have to either implement our own setting storage, or hack into the `ApplicationSettingsBase` so it could work in the way we expected - the shadow assembly should always use its "parent" assembly's settings. This is important for not only the "Start with Windows" switch, but also every setting we want to save.

Right now I'm working on the second choice, writing a custom `SettingsProvider` class for the shadow assembly. Hopefully with this approach, we could settle the settings sharing issue once and for all. Something similar will be done as in your pull request, the parent assembly's config file path will be passed to the shadow process, and some tricky code will reroute the setting classes to read and write values from this file.

**Comment by hillin** [comment]
After a deep dive into .NET's configuration system, I finally ended up  implementing a custom config system, along with an infrastructure to pass information from the parent process to the shadow assembly. Hopefully this will fix the setting sharing issues, as well as this one. I'm not taking this pull request, but again, thanks for your contribution!

**Comment by Nesquick0** [comment]
Thanks for fixing this. I'm happy either way.

**Pull request closed without merging**
